[2025-01-11 13:31:37,460: INFO: main: Welcome to our custom log]
[2025-01-11 17:57:42,060: INFO: main: Welcome to our custom log]
[2025-01-11 18:05:01,336: INFO: main: Welcome to our custom log]
[2025-01-14 19:41:22,665: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 19:41:22,693: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 19:41:22,696: INFO: common: created directory at: artifacts_root]
[2025-01-14 19:41:22,696: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:00:33,013: ERROR: 3638245915: An error occurred during data ingestion: DataIngestionConfig.__init__() missing 2 required positional arguments: 'root_dir' and 'unzip_dir']
[2025-01-14 20:06:13,346: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:06:13,354: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:06:13,361: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:06:13,365: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:08:19,014: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:08:19,018: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:08:19,023: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:08:19,026: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:09:28,198: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:09:28,202: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:09:28,206: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:09:28,208: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:10:35,763: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:10:35,768: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:10:35,769: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:10:35,769: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:12:19,402: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:12:19,406: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:12:19,407: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:12:19,407: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:19:48,543: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:19:48,547: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:19:48,552: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:19:48,556: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:20:19,110: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:20:19,114: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:20:19,117: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:20:19,121: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:27:20,875: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:27:20,879: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:27:20,888: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:27:20,892: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:27:20,896: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-14 20:27:47,592: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 20:27:47,596: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 20:27:47,599: INFO: common: created directory at: artifacts_root]
[2025-01-14 20:27:47,602: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 20:27:47,605: INFO: 3172177572: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-14 20:30:09,068: INFO: 3172177572: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-14 21:22:37,718: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-14 21:22:37,734: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-14 21:22:37,734: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-14 21:22:37,734: INFO: common: created directory at: artifacts_root]
[2025-01-14 21:22:37,738: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-14 21:22:37,739: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-14 21:25:13,962: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-14 21:25:14,835: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-17 20:02:20,207: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-17 20:02:20,208: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-17 20:02:20,218: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-17 20:02:20,220: INFO: common: created directory at: artifacts_root]
[2025-01-17 20:02:20,221: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-17 20:02:20,223: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-17 20:06:19,813: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-17 20:06:21,049: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-18 22:29:21,865: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-18 22:29:21,876: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-18 22:29:21,884: INFO: common: created directory at: artifacts_root]
[2025-01-18 22:29:21,884: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-01-18 22:42:30,263: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-18 22:42:30,270: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-18 22:42:30,272: INFO: common: created directory at: artifacts_root]
[2025-01-18 22:42:30,276: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-01-18 22:42:30,933: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-01-18 22:42:31,312: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-01-18 23:09:54,304: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-18 23:09:54,312: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-18 23:09:54,322: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-18 23:09:54,326: INFO: common: created directory at: artifacts_root]
[2025-01-18 23:09:54,342: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-18 23:09:54,346: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-18 23:15:34,799: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-18 23:15:36,413: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-18 23:15:36,413: INFO: main: *******************]
[2025-01-18 23:15:36,413: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-01-18 23:15:36,413: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-18 23:15:36,433: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-18 23:15:36,433: INFO: common: created directory at: artifacts_root]
[2025-01-18 23:15:36,437: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-01-18 23:15:36,438: ERROR: main: 'DataIngestion' object has no attribute 'get_base_model']
Traceback (most recent call last):
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\main.py", line 25, in <module>
    obj.main()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\pipeline\stage_02_prepare_base_model.py", line 16, in main
    prepare_base_model.get_base_model()
AttributeError: 'DataIngestion' object has no attribute 'get_base_model'
[2025-01-18 23:28:41,152: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-01-18 23:28:41,167: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-18 23:28:41,167: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-18 23:28:41,167: INFO: common: created directory at: artifacts_root]
[2025-01-18 23:28:41,172: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-01-18 23:28:41,174: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-18 23:34:19,500: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-01-18 23:34:20,894: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-01-18 23:34:20,910: INFO: main: *******************]
[2025-01-18 23:34:20,910: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-01-18 23:34:20,910: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-18 23:34:20,918: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-18 23:34:20,919: INFO: common: created directory at: artifacts_root]
[2025-01-18 23:34:20,920: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-01-18 23:34:22,911: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-01-18 23:34:23,237: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-01-18 23:34:23,443: INFO: main: Prepare Base Model completed]
[2025-01-19 01:21:11,205: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:21:11,216: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:21:11,216: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:24:46,450: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:24:46,464: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:24:46,471: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:25:31,408: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:25:31,416: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:25:31,422: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:28:54,872: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:28:54,879: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:28:54,882: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:31:07,342: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:31:07,349: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:31:07,352: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:33:05,181: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:33:05,187: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:33:05,190: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:33:53,096: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:33:53,109: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:33:53,112: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:34:20,445: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:34:20,451: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:34:20,453: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:37:31,022: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:37:31,028: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:37:31,031: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:39:58,751: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:39:58,760: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:39:58,763: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:40:20,042: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:40:20,053: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:40:20,058: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:40:50,410: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:40:50,417: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:40:50,425: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:41:08,201: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:41:08,214: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:41:08,214: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:43:35,768: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:43:35,775: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:43:35,779: INFO: common: created directory at: artifacts_root]
[2025-01-19 01:43:50,231: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-01-19 01:43:50,250: INFO: common: yaml file: params.yaml loaded successfully]
[2025-01-19 01:43:50,258: INFO: common: created directory at: artifacts_root]
[2025-02-18 19:04:33,264: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-18 19:04:33,270: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-18 19:04:33,291: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-18 19:04:33,293: INFO: common: created directory at: artifacts_root]
[2025-02-18 19:04:33,295: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-02-18 19:04:33,297: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-18 19:05:26,139: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-18 19:05:27,536: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-18 19:05:27,537: INFO: main: *******************]
[2025-02-18 19:05:27,538: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-02-18 19:05:27,544: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-18 19:05:27,547: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-18 19:05:27,548: INFO: common: created directory at: artifacts_root]
[2025-02-18 19:05:27,550: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-02-18 19:05:29,417: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-18 19:05:29,686: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-18 19:05:29,833: INFO: main: Prepare Base Model completed]
[2025-02-18 19:14:44,289: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-18 19:14:44,297: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-18 19:14:44,300: INFO: common: created directory at: artifacts_root]
[2025-02-18 19:14:44,303: INFO: common: created directory at: artifacts_root\training]
[2025-02-18 19:34:56,051: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-18 19:34:56,059: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-18 19:34:56,063: INFO: common: created directory at: artifacts_root]
[2025-02-18 19:34:56,066: INFO: common: created directory at: artifacts_root\training]
[2025-02-18 19:38:07,567: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-18 19:38:07,573: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-18 19:38:07,575: INFO: common: created directory at: artifacts_root]
[2025-02-18 19:38:07,578: INFO: common: created directory at: artifacts_root\training]
[2025-02-18 19:38:08,840: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-18 20:11:12,306: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-18 20:11:12,312: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-18 20:11:12,315: INFO: common: created directory at: artifacts_root]
[2025-02-18 20:11:12,318: INFO: common: created directory at: artifacts_root\training]
[2025-02-18 20:11:12,790: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-18 20:19:24,831: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-18 20:19:24,837: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-18 20:19:24,840: INFO: common: created directory at: artifacts_root]
[2025-02-18 20:19:24,842: INFO: common: created directory at: artifacts_root\training]
[2025-02-18 20:23:16,124: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-18 20:23:16,135: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-18 20:23:16,139: INFO: common: created directory at: artifacts_root]
[2025-02-18 20:23:16,143: INFO: common: created directory at: artifacts_root\training]
[2025-02-18 20:23:16,611: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-18 20:24:57,282: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-18 20:24:57,291: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-18 20:24:57,295: INFO: common: created directory at: artifacts_root]
[2025-02-18 20:24:57,298: INFO: common: created directory at: artifacts_root\training]
[2025-02-18 20:25:42,083: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-18 20:25:42,095: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-18 20:25:42,097: INFO: common: created directory at: artifacts_root]
[2025-02-18 20:25:42,103: INFO: common: created directory at: artifacts_root\training]
[2025-02-18 20:25:42,764: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-18 20:26:59,614: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-18 20:26:59,622: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-18 20:26:59,629: INFO: common: created directory at: artifacts_root]
[2025-02-18 20:26:59,632: INFO: common: created directory at: artifacts_root\training]
[2025-02-18 20:29:55,756: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 00:21:21,146: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-19 00:21:21,153: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 00:21:21,164: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 00:21:21,171: INFO: common: created directory at: artifacts_root]
[2025-02-19 00:21:21,176: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-02-19 00:21:21,179: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 00:22:32,835: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 00:22:34,484: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-19 00:22:34,484: INFO: main: *******************]
[2025-02-19 00:22:34,487: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-02-19 00:22:34,491: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 00:22:34,498: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 00:22:34,501: INFO: common: created directory at: artifacts_root]
[2025-02-19 00:22:34,507: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-02-19 00:22:35,247: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 00:22:35,802: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 00:22:35,988: INFO: main: Prepare Base Model completed]
[2025-02-19 00:22:35,988: INFO: main: *******************]
[2025-02-19 00:22:35,989: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-19 00:22:35,995: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 00:22:36,002: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 00:22:36,005: INFO: common: created directory at: artifacts_root]
[2025-02-19 00:22:36,008: INFO: common: created directory at: artifacts_root\training]
[2025-02-19 00:24:32,843: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 00:24:33,106: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-19 13:42:42,271: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-19 13:42:42,277: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 13:42:42,281: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 13:42:42,282: INFO: common: created directory at: artifacts_root]
[2025-02-19 13:42:42,283: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-02-19 13:42:42,284: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 13:44:59,071: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 13:45:01,608: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-19 13:45:01,609: INFO: main: *******************]
[2025-02-19 13:45:01,612: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-02-19 13:45:01,636: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 13:45:01,648: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 13:45:01,654: INFO: common: created directory at: artifacts_root]
[2025-02-19 13:45:01,660: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-02-19 13:45:03,240: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 13:45:03,658: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 13:45:04,145: INFO: main: Prepare Base Model completed]
[2025-02-19 13:45:04,148: INFO: main: *******************]
[2025-02-19 13:45:04,149: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-19 13:45:04,155: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 13:45:04,172: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 13:45:04,172: INFO: common: created directory at: artifacts_root]
[2025-02-19 13:45:04,185: INFO: common: created directory at: artifacts_root\training]
[2025-02-19 13:47:58,731: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 13:47:58,987: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-19 13:47:58,991: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-19 13:47:59,024: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 13:47:59,038: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 13:47:59,049: INFO: common: created directory at: artifacts_root]
[2025-02-19 13:47:59,836: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-19 13:48:59,964: INFO: common: JSON file saved at: scores.json]
[2025-02-19 13:50:00,699: ERROR: main: When an mlflow-artifacts URI was supplied, the tracking URI must be a valid http or https URI, but it was currently set to file:///C:/Users/Dell/python/PROJECT/MLOPS/Kidney-Disease/mlruns. Perhaps you forgot to set the tracking URI to the running MLflow server. To set the tracking URI, use either of the following methods:
1. Set the MLFLOW_TRACKING_URI environment variable to the desired tracking URI. `export MLFLOW_TRACKING_URI=http://localhost:5000`
2. Set the tracking URI programmatically by calling `mlflow.set_tracking_uri`. `mlflow.set_tracking_uri('http://localhost:5000')`]
Traceback (most recent call last):
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\main.py", line 53, in <module>
    obj.main()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\pipeline\stage_04_model_evaluation_with_mlflow.py", line 18, in main
    evaluation.log_into_mlflow()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\components\model_evaluation_mlflow.py", line 73, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\keras\save.py", line 339, in log_model
    return Model.log(
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\models\model.py", line 846, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path, run_id)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\fluent.py", line 1219, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\client.py", line 1982, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 875, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 817, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 131, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 76, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 51, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 65, in resolve_uri
    _validate_uri_scheme(track_parse)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: When an mlflow-artifacts URI was supplied, the tracking URI must be a valid http or https URI, but it was currently set to file:///C:/Users/Dell/python/PROJECT/MLOPS/Kidney-Disease/mlruns. Perhaps you forgot to set the tracking URI to the running MLflow server. To set the tracking URI, use either of the following methods:
1. Set the MLFLOW_TRACKING_URI environment variable to the desired tracking URI. `export MLFLOW_TRACKING_URI=http://localhost:5000`
2. Set the tracking URI programmatically by calling `mlflow.set_tracking_uri`. `mlflow.set_tracking_uri('http://localhost:5000')`
[2025-02-19 14:04:49,722: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-19 14:04:49,736: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 14:04:49,746: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 14:04:49,746: INFO: common: created directory at: artifacts_root]
[2025-02-19 14:04:49,746: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-02-19 14:04:49,746: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 14:05:50,147: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 14:05:51,515: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-19 14:05:51,516: INFO: main: *******************]
[2025-02-19 14:05:51,516: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-02-19 14:05:51,518: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 14:05:51,524: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 14:05:51,525: INFO: common: created directory at: artifacts_root]
[2025-02-19 14:05:51,526: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-02-19 14:05:53,031: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 14:05:53,458: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 14:05:53,681: INFO: main: Prepare Base Model completed]
[2025-02-19 14:05:53,683: INFO: main: *******************]
[2025-02-19 14:05:53,690: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-19 14:05:53,709: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 14:05:53,717: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 14:05:53,719: INFO: common: created directory at: artifacts_root]
[2025-02-19 14:05:53,719: INFO: common: created directory at: artifacts_root\training]
[2025-02-19 14:09:10,913: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 14:09:11,172: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-19 14:09:11,174: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-19 14:09:11,186: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 14:09:11,195: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 14:09:11,201: INFO: common: created directory at: artifacts_root]
[2025-02-19 14:09:11,619: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-19 14:10:07,391: INFO: common: JSON file saved at: scores.json]
[2025-02-19 14:10:58,943: ERROR: main: When an mlflow-artifacts URI was supplied, the tracking URI must be a valid http or https URI, but it was currently set to file:///C:/Users/Dell/python/PROJECT/MLOPS/Kidney-Disease/mlruns. Perhaps you forgot to set the tracking URI to the running MLflow server. To set the tracking URI, use either of the following methods:
1. Set the MLFLOW_TRACKING_URI environment variable to the desired tracking URI. `export MLFLOW_TRACKING_URI=http://localhost:5000`
2. Set the tracking URI programmatically by calling `mlflow.set_tracking_uri`. `mlflow.set_tracking_uri('http://localhost:5000')`]
Traceback (most recent call last):
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\main.py", line 53, in <module>
    obj.main()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\pipeline\stage_04_model_evaluation_with_mlflow.py", line 18, in main
    evaluation.log_into_mlflow()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\components\model_evaluation_mlflow.py", line 73, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\keras\save.py", line 339, in log_model
    return Model.log(
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\models\model.py", line 846, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path, run_id)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\fluent.py", line 1219, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\client.py", line 1982, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 875, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 817, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 131, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 76, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 51, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 65, in resolve_uri
    _validate_uri_scheme(track_parse)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: When an mlflow-artifacts URI was supplied, the tracking URI must be a valid http or https URI, but it was currently set to file:///C:/Users/Dell/python/PROJECT/MLOPS/Kidney-Disease/mlruns. Perhaps you forgot to set the tracking URI to the running MLflow server. To set the tracking URI, use either of the following methods:
1. Set the MLFLOW_TRACKING_URI environment variable to the desired tracking URI. `export MLFLOW_TRACKING_URI=http://localhost:5000`
2. Set the tracking URI programmatically by calling `mlflow.set_tracking_uri`. `mlflow.set_tracking_uri('http://localhost:5000')`
[2025-02-19 21:15:16,874: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-19 21:15:16,874: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 21:15:16,899: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 21:15:16,902: INFO: common: created directory at: artifacts_root]
[2025-02-19 21:15:16,903: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-02-19 21:15:16,903: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 21:16:00,071: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 21:16:02,618: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-19 21:16:02,634: INFO: main: *******************]
[2025-02-19 21:16:02,634: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-02-19 21:16:02,646: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 21:16:02,653: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 21:16:02,654: INFO: common: created directory at: artifacts_root]
[2025-02-19 21:16:02,655: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-02-19 21:16:05,032: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 21:16:05,574: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 21:16:05,808: INFO: main: Prepare Base Model completed]
[2025-02-19 21:16:05,808: INFO: main: *******************]
[2025-02-19 21:16:05,808: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-19 21:16:05,808: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 21:16:05,833: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 21:16:05,834: INFO: common: created directory at: artifacts_root]
[2025-02-19 21:16:05,836: INFO: common: created directory at: artifacts_root\training]
[2025-02-19 21:18:28,653: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 21:18:28,904: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-19 21:18:28,904: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-19 21:18:28,904: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 21:18:28,925: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 21:18:28,926: INFO: common: created directory at: artifacts_root]
[2025-02-19 21:18:29,440: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-19 21:19:15,231: INFO: common: JSON file saved at: scores.json]
[2025-02-19 21:19:54,905: ERROR: main: When an mlflow-artifacts URI was supplied, the tracking URI must be a valid http or https URI, but it was currently set to file:///C:/Users/Dell/python/PROJECT/MLOPS/Kidney-Disease/mlruns. Perhaps you forgot to set the tracking URI to the running MLflow server. To set the tracking URI, use either of the following methods:
1. Set the MLFLOW_TRACKING_URI environment variable to the desired tracking URI. `export MLFLOW_TRACKING_URI=http://localhost:5000`
2. Set the tracking URI programmatically by calling `mlflow.set_tracking_uri`. `mlflow.set_tracking_uri('http://localhost:5000')`]
Traceback (most recent call last):
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\main.py", line 53, in <module>
    obj.main()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\pipeline\stage_04_model_evaluation_with_mlflow.py", line 18, in main
    evaluation.log_into_mlflow()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\components\model_evaluation_mlflow.py", line 73, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\keras\save.py", line 339, in log_model
    return Model.log(
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\models\model.py", line 846, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path, run_id)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\fluent.py", line 1219, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\client.py", line 1982, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 875, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 817, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 131, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 76, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 51, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 65, in resolve_uri
    _validate_uri_scheme(track_parse)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: When an mlflow-artifacts URI was supplied, the tracking URI must be a valid http or https URI, but it was currently set to file:///C:/Users/Dell/python/PROJECT/MLOPS/Kidney-Disease/mlruns. Perhaps you forgot to set the tracking URI to the running MLflow server. To set the tracking URI, use either of the following methods:
1. Set the MLFLOW_TRACKING_URI environment variable to the desired tracking URI. `export MLFLOW_TRACKING_URI=http://localhost:5000`
2. Set the tracking URI programmatically by calling `mlflow.set_tracking_uri`. `mlflow.set_tracking_uri('http://localhost:5000')`
[2025-02-19 21:25:00,672: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-19 21:25:00,672: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 21:25:00,690: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 21:25:00,691: INFO: common: created directory at: artifacts_root]
[2025-02-19 21:25:00,692: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-02-19 21:25:00,693: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 21:28:14,492: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 21:28:15,530: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-19 21:28:15,530: INFO: main: *******************]
[2025-02-19 21:28:15,530: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-02-19 21:28:15,544: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 21:28:15,549: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 21:28:15,550: INFO: common: created directory at: artifacts_root]
[2025-02-19 21:28:15,551: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-02-19 21:28:16,972: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 21:28:17,288: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 21:28:17,437: INFO: main: Prepare Base Model completed]
[2025-02-19 21:28:17,437: INFO: main: *******************]
[2025-02-19 21:28:17,437: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-19 21:28:17,453: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 21:28:17,458: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 21:28:17,460: INFO: common: created directory at: artifacts_root]
[2025-02-19 21:28:17,461: INFO: common: created directory at: artifacts_root\training]
[2025-02-19 21:30:10,416: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 21:30:10,562: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-19 21:30:10,562: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-19 21:30:10,562: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 21:30:10,576: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 21:30:10,578: INFO: common: created directory at: artifacts_root]
[2025-02-19 21:30:10,880: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-19 21:30:45,605: INFO: common: JSON file saved at: scores.json]
[2025-02-19 21:33:10,446: INFO: common: JSON file saved at: scores.json]
[2025-02-19 21:33:10,458: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-19 21:36:14,409: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-19 21:36:14,430: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 21:36:14,441: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 21:36:14,445: INFO: common: created directory at: artifacts_root]
[2025-02-19 21:36:14,445: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-02-19 21:36:14,453: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 21:37:24,658: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 21:37:26,087: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-19 21:37:26,104: INFO: main: *******************]
[2025-02-19 21:37:26,105: INFO: main: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-02-19 21:37:26,109: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 21:37:26,112: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 21:37:26,114: INFO: common: created directory at: artifacts_root]
[2025-02-19 21:37:26,117: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-02-19 21:37:27,255: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 21:37:27,529: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 21:37:27,670: INFO: main: Prepare Base Model completed]
[2025-02-19 21:37:27,670: INFO: main: *******************]
[2025-02-19 21:37:27,670: INFO: main: >>>>>> stage Training started <<<<<<]
[2025-02-19 21:37:27,670: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 21:37:27,688: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 21:37:27,691: INFO: common: created directory at: artifacts_root]
[2025-02-19 21:37:27,694: INFO: common: created directory at: artifacts_root\training]
[2025-02-19 21:43:17,105: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 21:43:17,270: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-19 21:43:17,270: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-19 21:43:17,270: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 21:43:17,292: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 21:43:17,292: INFO: common: created directory at: artifacts_root]
[2025-02-19 21:43:17,670: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-19 21:43:56,558: INFO: common: JSON file saved at: scores.json]
[2025-02-19 21:46:24,600: INFO: common: JSON file saved at: scores.json]
[2025-02-19 21:46:24,600: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-19 23:51:36,513: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-19 23:51:36,523: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 23:51:36,536: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 23:51:36,536: INFO: common: created directory at: artifacts_root]
[2025-02-19 23:51:36,540: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-02-19 23:51:36,542: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 23:53:45,538: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-19 23:53:45,541: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 23:53:45,554: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 23:53:45,555: INFO: common: created directory at: artifacts_root]
[2025-02-19 23:53:45,555: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-02-19 23:53:45,557: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 23:55:22,700: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-19 23:55:24,918: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-19 23:57:30,182: INFO: stage_02_prepare_base_model: *******************]
[2025-02-19 23:57:30,183: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-02-19 23:57:30,186: INFO: stage_02_prepare_base_model: Prepare Base Model started]
[2025-02-19 23:57:30,192: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 23:57:30,215: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 23:57:30,225: INFO: common: created directory at: artifacts_root]
[2025-02-19 23:57:30,239: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-02-19 23:57:32,554: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 23:57:32,995: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-19 23:57:33,252: INFO: stage_02_prepare_base_model: Prepare Base Model completed]
[2025-02-19 23:57:52,446: INFO: stage_03_model_training: *******************]
[2025-02-19 23:57:52,447: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-02-19 23:57:52,450: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-19 23:57:52,467: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-19 23:57:52,470: INFO: common: created directory at: artifacts_root]
[2025-02-19 23:57:52,472: INFO: common: created directory at: artifacts_root\training]
[2025-02-20 00:05:18,476: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-20 00:05:18,866: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-20 00:05:44,632: INFO: stage_04_model_evaluation_with_mlflow: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-20 00:05:44,637: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-20 00:05:44,643: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-20 00:05:44,644: INFO: common: created directory at: artifacts_root]
[2025-02-20 00:05:45,245: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 00:06:39,603: INFO: common: JSON file saved at: scores.json]
[2025-02-20 00:07:13,769: ERROR: stage_04_model_evaluation_with_mlflow: When an mlflow-artifacts URI was supplied, the tracking URI must be a valid http or https URI, but it was currently set to file:///C:/Users/Dell/python/PROJECT/MLOPS/Kidney-Disease/mlruns. Perhaps you forgot to set the tracking URI to the running MLflow server. To set the tracking URI, use either of the following methods:
1. Set the MLFLOW_TRACKING_URI environment variable to the desired tracking URI. `export MLFLOW_TRACKING_URI=http://localhost:5000`
2. Set the tracking URI programmatically by calling `mlflow.set_tracking_uri`. `mlflow.set_tracking_uri('http://localhost:5000')`]
Traceback (most recent call last):
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\pipeline\stage_04_model_evaluation_with_mlflow.py", line 33, in <module>
    obj.main()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\pipeline\stage_04_model_evaluation_with_mlflow.py", line 24, in main
    evaluation.log_into_mlflow()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\components\model_evaluation_mlflow.py", line 73, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\keras\save.py", line 339, in log_model
    return Model.log(
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\models\model.py", line 846, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path, run_id)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\fluent.py", line 1219, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\client.py", line 1982, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 875, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 817, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 131, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 76, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 51, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 65, in resolve_uri
    _validate_uri_scheme(track_parse)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: When an mlflow-artifacts URI was supplied, the tracking URI must be a valid http or https URI, but it was currently set to file:///C:/Users/Dell/python/PROJECT/MLOPS/Kidney-Disease/mlruns. Perhaps you forgot to set the tracking URI to the running MLflow server. To set the tracking URI, use either of the following methods:
1. Set the MLFLOW_TRACKING_URI environment variable to the desired tracking URI. `export MLFLOW_TRACKING_URI=http://localhost:5000`
2. Set the tracking URI programmatically by calling `mlflow.set_tracking_uri`. `mlflow.set_tracking_uri('http://localhost:5000')`
[2025-02-20 00:13:18,797: INFO: stage_04_model_evaluation_with_mlflow: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-20 00:13:18,800: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-20 00:13:18,809: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-20 00:13:18,810: INFO: common: created directory at: artifacts_root]
[2025-02-20 00:13:19,406: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 00:14:15,949: INFO: common: JSON file saved at: scores.json]
[2025-02-20 00:14:46,401: ERROR: stage_04_model_evaluation_with_mlflow: When an mlflow-artifacts URI was supplied, the tracking URI must be a valid http or https URI, but it was currently set to file:///C:/Users/Dell/python/PROJECT/MLOPS/Kidney-Disease/mlruns. Perhaps you forgot to set the tracking URI to the running MLflow server. To set the tracking URI, use either of the following methods:
1. Set the MLFLOW_TRACKING_URI environment variable to the desired tracking URI. `export MLFLOW_TRACKING_URI=http://localhost:5000`
2. Set the tracking URI programmatically by calling `mlflow.set_tracking_uri`. `mlflow.set_tracking_uri('http://localhost:5000')`]
Traceback (most recent call last):
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\pipeline\stage_04_model_evaluation_with_mlflow.py", line 33, in <module>
    obj.main()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\pipeline\stage_04_model_evaluation_with_mlflow.py", line 24, in main
    evaluation.log_into_mlflow()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\components\model_evaluation_mlflow.py", line 73, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\keras\save.py", line 339, in log_model
    return Model.log(
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\models\model.py", line 846, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path, run_id)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\fluent.py", line 1219, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\client.py", line 1982, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 875, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 817, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 131, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 76, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 51, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 65, in resolve_uri
    _validate_uri_scheme(track_parse)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: When an mlflow-artifacts URI was supplied, the tracking URI must be a valid http or https URI, but it was currently set to file:///C:/Users/Dell/python/PROJECT/MLOPS/Kidney-Disease/mlruns. Perhaps you forgot to set the tracking URI to the running MLflow server. To set the tracking URI, use either of the following methods:
1. Set the MLFLOW_TRACKING_URI environment variable to the desired tracking URI. `export MLFLOW_TRACKING_URI=http://localhost:5000`
2. Set the tracking URI programmatically by calling `mlflow.set_tracking_uri`. `mlflow.set_tracking_uri('http://localhost:5000')`
[2025-02-20 00:19:36,196: INFO: stage_04_model_evaluation_with_mlflow: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-20 00:19:36,207: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-20 00:19:36,211: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-20 00:19:36,213: INFO: common: created directory at: artifacts_root]
[2025-02-20 00:19:36,795: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 00:21:01,229: INFO: common: JSON file saved at: scores.json]
[2025-02-20 00:21:34,754: ERROR: stage_04_model_evaluation_with_mlflow: When an mlflow-artifacts URI was supplied, the tracking URI must be a valid http or https URI, but it was currently set to file:///C:/Users/Dell/python/PROJECT/MLOPS/Kidney-Disease/mlruns. Perhaps you forgot to set the tracking URI to the running MLflow server. To set the tracking URI, use either of the following methods:
1. Set the MLFLOW_TRACKING_URI environment variable to the desired tracking URI. `export MLFLOW_TRACKING_URI=http://localhost:5000`
2. Set the tracking URI programmatically by calling `mlflow.set_tracking_uri`. `mlflow.set_tracking_uri('http://localhost:5000')`]
Traceback (most recent call last):
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\pipeline\stage_04_model_evaluation_with_mlflow.py", line 33, in <module>
    obj.main()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\pipeline\stage_04_model_evaluation_with_mlflow.py", line 24, in main
    evaluation.log_into_mlflow()
  File "C:\Users\Dell\python\PROJECT\MLOPS\Kidney-Disease\src\CNNclassifier\components\model_evaluation_mlflow.py", line 73, in log_into_mlflow
    mlflow.keras.log_model(self.model, "model")
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\keras\save.py", line 339, in log_model
    return Model.log(
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\models\model.py", line 846, in log
    mlflow.tracking.fluent.log_artifacts(local_path, mlflow_model.artifact_path, run_id)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\fluent.py", line 1219, in log_artifacts
    MlflowClient().log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\client.py", line 1982, in log_artifacts
    self._tracking_client.log_artifacts(run_id, local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 875, in log_artifacts
    self._get_artifact_repo(run_id).log_artifacts(local_dir, artifact_path)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 817, in _get_artifact_repo
    artifact_repo = get_artifact_repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 131, in get_artifact_repository
    return _artifact_repository_registry.get_artifact_repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\artifact_repository_registry.py", line 76, in get_artifact_repository
    return repository(artifact_uri)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 51, in __init__
    super().__init__(self.resolve_uri(artifact_uri, get_tracking_uri()))
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 65, in resolve_uri
    _validate_uri_scheme(track_parse)
  File "C:\Users\Dell\anaconda3\envs\deep\lib\site-packages\mlflow\store\artifact\mlflow_artifacts_repo.py", line 35, in _validate_uri_scheme
    raise MlflowException(
mlflow.exceptions.MlflowException: When an mlflow-artifacts URI was supplied, the tracking URI must be a valid http or https URI, but it was currently set to file:///C:/Users/Dell/python/PROJECT/MLOPS/Kidney-Disease/mlruns. Perhaps you forgot to set the tracking URI to the running MLflow server. To set the tracking URI, use either of the following methods:
1. Set the MLFLOW_TRACKING_URI environment variable to the desired tracking URI. `export MLFLOW_TRACKING_URI=http://localhost:5000`
2. Set the tracking URI programmatically by calling `mlflow.set_tracking_uri`. `mlflow.set_tracking_uri('http://localhost:5000')`
[2025-02-20 00:34:59,891: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage started <<<<<<]
[2025-02-20 00:34:59,891: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-20 00:34:59,910: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-20 00:34:59,911: INFO: common: created directory at: artifacts_root]
[2025-02-20 00:34:59,914: INFO: common: created directory at: artifacts_root/data_ingestion]
[2025-02-20 00:34:59,914: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-20 00:36:35,357: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts_root/data_ingestion/data.zip]
[2025-02-20 00:36:36,984: INFO: stage_01_data_ingestion: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2025-02-20 00:36:57,731: INFO: stage_02_prepare_base_model: *******************]
[2025-02-20 00:36:57,731: INFO: stage_02_prepare_base_model: >>>>>> stage Prepare Base Model started <<<<<<]
[2025-02-20 00:36:57,731: INFO: stage_02_prepare_base_model: Prepare Base Model started]
[2025-02-20 00:36:57,731: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-20 00:36:57,750: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-20 00:36:57,752: INFO: common: created directory at: artifacts_root]
[2025-02-20 00:36:57,753: INFO: common: created directory at: artifacts_root/prepare_base_model]
[2025-02-20 00:36:59,481: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-20 00:36:59,884: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-20 00:37:00,097: INFO: stage_02_prepare_base_model: Prepare Base Model completed]
[2025-02-20 00:37:16,743: INFO: stage_03_model_training: *******************]
[2025-02-20 00:37:16,743: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-02-20 00:37:16,760: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-20 00:37:16,769: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-20 00:37:16,770: INFO: common: created directory at: artifacts_root]
[2025-02-20 00:37:16,771: INFO: common: created directory at: artifacts_root\training]
[2025-02-20 00:42:00,790: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-20 00:42:01,022: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-20 00:43:34,940: INFO: stage_04_model_evaluation_with_mlflow: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-20 00:43:34,940: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-20 00:43:34,957: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-20 00:43:34,959: INFO: common: created directory at: artifacts_root]
[2025-02-20 00:43:35,556: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 00:44:16,174: INFO: common: JSON file saved at: scores.json]
[2025-02-20 00:47:53,561: INFO: common: JSON file saved at: scores.json]
[2025-02-20 00:47:53,561: INFO: stage_04_model_evaluation_with_mlflow: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-20 00:49:31,931: INFO: stage_04_model_evaluation_with_mlflow: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-20 00:49:31,931: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-20 00:49:31,946: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-20 00:49:31,948: INFO: common: created directory at: artifacts_root]
[2025-02-20 00:49:32,598: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 00:50:19,503: INFO: common: JSON file saved at: scores.json]
[2025-02-20 00:52:39,156: INFO: common: JSON file saved at: scores.json]
[2025-02-20 00:52:39,156: INFO: stage_04_model_evaluation_with_mlflow: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-20 02:45:27,620: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.90.156:8080]
[2025-02-20 02:45:27,624: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-20 02:45:27,633: INFO: _internal:  * Restarting with stat]
[2025-02-20 02:45:41,611: WARNING: _internal:  * Debugger is active!]
[2025-02-20 02:45:41,630: INFO: _internal:  * Debugger PIN: 248-427-198]
[2025-02-20 02:45:48,793: INFO: _internal: 192.168.90.156 - - [20/Feb/2025 02:45:48] "GET / HTTP/1.1" 200 -]
[2025-02-20 02:45:48,897: INFO: _internal: 192.168.90.156 - - [20/Feb/2025 02:45:48] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-02-20 02:45:59,761: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 02:45:59] "GET / HTTP/1.1" 200 -]
[2025-02-20 02:45:59,859: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 02:45:59] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-02-20 02:46:02,450: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 02:46:02] "GET / HTTP/1.1" 200 -]
[2025-02-20 02:46:45,368: INFO: _internal: 192.168.90.156 - - [20/Feb/2025 02:46:45] "GET / HTTP/1.1" 200 -]
[2025-02-20 02:47:05,644: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 02:47:05] "GET / HTTP/1.1" 200 -]
[2025-02-20 02:47:26,969: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 02:47:26] "GET / HTTP/1.1" 200 -]
[2025-02-20 02:47:32,626: INFO: _internal: 192.168.90.156 - - [20/Feb/2025 02:47:32] "GET / HTTP/1.1" 200 -]
[2025-02-20 02:47:47,087: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 02:47:51,459: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 02:47:51] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 02:49:24,504: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 02:49:26,836: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 02:49:26] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 02:49:37,283: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 02:49:39,576: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 02:49:39] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 02:49:56,645: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 02:49:59,076: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 02:49:59] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 02:50:07,773: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 02:50:10,265: WARNING: polymorphic_function: 5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000002AE0FD5E3B0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-02-20 02:50:10,333: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 02:50:10] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 02:50:22,139: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 02:50:24,576: WARNING: polymorphic_function: 6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000002AE0634A5F0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-02-20 02:50:25,028: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 02:50:25] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 02:50:39,656: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 02:50:42,213: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 02:50:42] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 02:52:11,387: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 02:52:14,275: INFO: _internal: 192.168.90.156 - - [20/Feb/2025 02:52:14] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 02:52:29,203: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 02:52:31,766: INFO: _internal: 192.168.90.156 - - [20/Feb/2025 02:52:31] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 02:54:57,771: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 02:55:00,667: INFO: _internal: 192.168.90.156 - - [20/Feb/2025 02:55:00] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 02:55:10,648: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 02:55:12,919: INFO: _internal: 192.168.90.156 - - [20/Feb/2025 02:55:12] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 02:59:17,705: INFO: stage_03_model_training: *******************]
[2025-02-20 02:59:17,706: INFO: stage_03_model_training: >>>>>> stage Training started <<<<<<]
[2025-02-20 02:59:17,715: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-20 02:59:17,730: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-20 02:59:17,734: INFO: common: created directory at: artifacts_root]
[2025-02-20 02:59:17,737: INFO: common: created directory at: artifacts_root\training]
[2025-02-20 03:11:33,686: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-02-20 03:11:34,162: INFO: stage_03_model_training: >>>>>> stage Training completed <<<<<<

x==========x]
[2025-02-20 03:12:09,058: INFO: stage_04_model_evaluation_with_mlflow: >>>>>> stage Evaluation stage started <<<<<<]
[2025-02-20 03:12:09,066: INFO: common: yaml file: configs\config.yaml loaded successfully]
[2025-02-20 03:12:09,074: INFO: common: yaml file: params.yaml loaded successfully]
[2025-02-20 03:12:09,076: INFO: common: created directory at: artifacts_root]
[2025-02-20 03:12:09,873: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 03:13:05,406: INFO: common: JSON file saved at: scores.json]
[2025-02-20 03:15:32,148: INFO: common: JSON file saved at: scores.json]
[2025-02-20 03:15:32,150: INFO: stage_04_model_evaluation_with_mlflow: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2025-02-20 03:16:10,975: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.90.156:8080]
[2025-02-20 03:16:10,977: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-20 03:16:10,978: INFO: _internal:  * Restarting with stat]
[2025-02-20 03:16:21,772: WARNING: _internal:  * Debugger is active!]
[2025-02-20 03:16:21,772: INFO: _internal:  * Debugger PIN: 248-427-198]
[2025-02-20 03:16:26,892: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:16:26] "GET / HTTP/1.1" 200 -]
[2025-02-20 03:19:32,619: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:19:32] "GET / HTTP/1.1" 200 -]
[2025-02-20 03:19:39,575: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 03:19:41,641: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:19:41] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:20:00,816: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 03:20:02,638: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:20:02] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:24:45,658: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:24:45] "GET / HTTP/1.1" 200 -]
[2025-02-20 03:24:53,121: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:24:53] "[31m[1mPOST /predict HTTP/1.1[0m" 415 -]
[2025-02-20 03:29:50,101: INFO: _internal:  * Detected change in 'C:\\Users\\Dell\\python\\PROJECT\\MLOPS\\Kidney-Disease\\app.py', reloading]
[2025-02-20 03:29:51,965: INFO: _internal:  * Restarting with stat]
[2025-02-20 03:30:11,025: WARNING: _internal:  * Debugger is active!]
[2025-02-20 03:30:11,025: INFO: _internal:  * Debugger PIN: 248-427-198]
[2025-02-20 03:30:21,299: INFO: _internal:  * Detected change in 'C:\\Users\\Dell\\python\\PROJECT\\MLOPS\\Kidney-Disease\\app.py', reloading]
[2025-02-20 03:30:22,590: INFO: _internal:  * Restarting with stat]
[2025-02-20 03:30:36,726: WARNING: _internal:  * Debugger is active!]
[2025-02-20 03:30:36,736: INFO: _internal:  * Debugger PIN: 248-427-198]
[2025-02-20 03:34:17,618: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:34:17] "GET / HTTP/1.1" 200 -]
[2025-02-20 03:34:24,364: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 03:34:26,125: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:34:26] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:34:37,227: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 03:34:40,007: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:34:40] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:35:03,696: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 03:35:06,507: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:35:06] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:35:17,913: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-02-20 03:35:19,512: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:35:19] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:38:49,331: INFO: _internal:  * Detected change in 'C:\\Users\\Dell\\python\\PROJECT\\MLOPS\\Kidney-Disease\\src\\CNNclassifier\\pipeline\\prediction.py', reloading]
[2025-02-20 03:38:51,437: INFO: _internal:  * Restarting with stat]
[2025-02-20 03:40:03,133: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.90.156:8080]
[2025-02-20 03:40:03,134: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-20 03:40:03,141: INFO: _internal:  * Restarting with stat]
[2025-02-20 03:40:16,813: WARNING: _internal:  * Debugger is active!]
[2025-02-20 03:40:16,821: INFO: _internal:  * Debugger PIN: 248-427-198]
[2025-02-20 03:40:17,526: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:40:17] "GET / HTTP/1.1" 200 -]
[2025-02-20 03:40:28,392: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:40:28] "GET / HTTP/1.1" 200 -]
[2025-02-20 03:40:55,078: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:40:55] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:41:03,392: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:41:03] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:41:59,328: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:41:59] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:42:09,353: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:42:09] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:42:38,664: INFO: _internal:  * Detected change in 'C:\\Users\\Dell\\python\\PROJECT\\MLOPS\\Kidney-Disease\\src\\CNNclassifier\\pipeline\\prediction.py', reloading]
[2025-02-20 03:42:40,077: INFO: _internal:  * Restarting with stat]
[2025-02-20 03:42:54,037: WARNING: _internal:  * Debugger is active!]
[2025-02-20 03:42:54,053: INFO: _internal:  * Debugger PIN: 248-427-198]
[2025-02-20 03:42:54,698: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:42:54] "GET / HTTP/1.1" 200 -]
[2025-02-20 03:43:07,267: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:43:07] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:43:18,682: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:43:18] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:43:30,968: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:43:30] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:43:41,608: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:43:41] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:43:55,999: WARNING: polymorphic_function: 5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001B901875A20> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2025-02-20 03:43:56,041: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:43:56] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:45:59,198: INFO: _internal:  * Detected change in 'C:\\Users\\Dell\\python\\PROJECT\\MLOPS\\Kidney-Disease\\src\\CNNclassifier\\pipeline\\prediction.py', reloading]
[2025-02-20 03:46:01,227: INFO: _internal:  * Restarting with stat]
[2025-02-20 03:46:21,343: WARNING: _internal:  * Debugger is active!]
[2025-02-20 03:46:21,355: INFO: _internal:  * Debugger PIN: 248-427-198]
[2025-02-20 03:46:45,672: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:46:45] "GET / HTTP/1.1" 200 -]
[2025-02-20 03:46:51,899: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:46:51] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-02-20 03:47:01,383: INFO: _internal:  * Detected change in 'C:\\Users\\Dell\\python\\PROJECT\\MLOPS\\Kidney-Disease\\src\\CNNclassifier\\pipeline\\prediction.py', reloading]
[2025-02-20 03:47:02,351: INFO: _internal:  * Restarting with stat]
[2025-02-20 03:47:14,096: WARNING: _internal:  * Debugger is active!]
[2025-02-20 03:47:14,104: INFO: _internal:  * Debugger PIN: 248-427-198]
[2025-02-20 03:47:26,697: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:47:26] "GET / HTTP/1.1" 200 -]
[2025-02-20 03:47:33,396: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:47:33] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-02-20 03:47:35,161: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:47:35] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2025-02-20 03:48:31,511: INFO: _internal:  * Detected change in 'C:\\Users\\Dell\\python\\PROJECT\\MLOPS\\Kidney-Disease\\src\\CNNclassifier\\pipeline\\prediction.py', reloading]
[2025-02-20 03:48:32,536: INFO: _internal:  * Restarting with stat]
[2025-02-20 03:48:46,665: WARNING: _internal:  * Debugger is active!]
[2025-02-20 03:48:46,685: INFO: _internal:  * Debugger PIN: 248-427-198]
[2025-02-20 03:49:01,913: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:49:01] "GET / HTTP/1.1" 200 -]
[2025-02-20 03:49:23,175: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:49:23] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 03:49:32,528: INFO: _internal: 127.0.0.1 - - [20/Feb/2025 03:49:32] "POST /predict HTTP/1.1" 200 -]
[2025-02-20 15:39:00,786: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.90.156:8080]
[2025-02-20 15:39:00,794: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-20 15:39:00,807: INFO: _internal:  * Restarting with stat]
[2025-02-20 15:39:16,441: WARNING: _internal:  * Debugger is active!]
[2025-02-20 15:39:16,450: INFO: _internal:  * Debugger PIN: 248-427-198]
[2025-02-20 15:39:21,776: INFO: _internal: 192.168.90.156 - - [20/Feb/2025 15:39:21] "GET / HTTP/1.1" 200 -]
[2025-02-20 15:39:23,264: INFO: _internal: 192.168.90.156 - - [20/Feb/2025 15:39:23] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-02-20 15:40:12,541: INFO: _internal: 192.168.90.156 - - [20/Feb/2025 15:40:12] "POST /predict HTTP/1.1" 200 -]
[2025-02-22 11:22:28,763: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.90.156:8080]
[2025-02-22 11:22:28,772: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2025-02-22 11:22:28,789: INFO: _internal:  * Restarting with stat]
[2025-02-22 11:22:40,153: WARNING: _internal:  * Debugger is active!]
[2025-02-22 11:22:40,153: INFO: _internal:  * Debugger PIN: 248-427-198]
[2025-02-22 11:23:00,647: INFO: _internal: 127.0.0.1 - - [22/Feb/2025 11:23:00] "GET / HTTP/1.1" 200 -]
[2025-02-22 11:23:01,671: INFO: _internal: 127.0.0.1 - - [22/Feb/2025 11:23:01] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -]
[2025-02-22 11:23:17,308: INFO: _internal: 127.0.0.1 - - [22/Feb/2025 11:23:17] "POST /predict HTTP/1.1" 200 -]
[2025-02-22 11:23:46,158: INFO: _internal: 127.0.0.1 - - [22/Feb/2025 11:23:46] "POST /predict HTTP/1.1" 200 -]
